name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npm install, build, and test
        run: |
          npm run build-all
        env:
          CI: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: |
          npx semantic-release
          cd packages/graphql-vision-plugin && npx semantic-release
          cd ..
          cd packages/graphql-vision-react-dashboard && npx semantic-release
